#KEYWORDS FOR MYSQL DB CONNECTION TO DJANGO

MYSQL_ENGINE = 'django.db.backends.mysql'
MYSQL_NAME = 'SMParking'
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = '3306'
MYSQL_USER = 'root'
MYSQL_PASSWORD = 'root'
