# Generated by Django 3.2.9 on 2021-11-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id_estacionamento', models.AutoField(primary_key=True, serialize=False)),
                ('razão_social_estacionamento', models.CharField(max_length=100)),
                ('nome_fantasia_estacionamento', models.CharField(max_length=25, unique=True)),
                ('cnpj_estacionamento', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'estacionamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id_estadia', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saída', models.DateTimeField()),
            ],
            options={
                'db_table': 'estadia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fantasia_fabricante', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'fabricante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Porte',
            fields=[
                ('id_porte', models.AutoField(primary_key=True, serialize=False)),
                ('nome_porte', models.CharField(max_length=15, unique=True)),
                ('sigla_porte', models.CharField(max_length=2, unique=True)),
                ('valor_hora', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'porte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id_vaga', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vaga', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'vaga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veículo',
            fields=[
                ('id_veículo', models.AutoField(primary_key=True, serialize=False)),
                ('chapa_veículo', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'veículo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='área',
            fields=[
                ('id_área', models.AutoField(primary_key=True, serialize=False)),
                ('nome_área', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'área',
                'managed': False,
            },
        ),
    ]
