# Generated by Django 3.2.9 on 2021-11-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'área',
                'managed': False,
            },
        ),
    ]
