# Generated by Django 3.2.9 on 2021-11-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_vagalivre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vagalivre',
            table='vagalivre',
        ),
    ]
