# Generated by Django 3.2.9 on 2021-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_alter_vagalivre_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupada',
            fields=[
                ('id_estadia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fk_vaga', models.IntegerField(verbose_name='fk_vaga')),
                ('fk_veículo', models.IntegerField(verbose_name='fk_veículo')),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saída', models.DateTimeField()),
            ],
            options={
                'db_table': 'ocupada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocupação',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_vaga', models.IntegerField(verbose_name='id_vaga')),
                ('nome_vaga', models.CharField(max_length=10, verbose_name='nome_vaga')),
                ('nome_área', models.CharField(max_length=10, verbose_name='nome_área')),
                ('chapa_veículo', models.CharField(max_length=7, verbose_name='chapa_veículo')),
                ('id_estadia', models.IntegerField(verbose_name='id_estadia')),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saída', models.DateTimeField()),
                ('duração_estimada', models.BigIntegerField(verbose_name='ocupação_estimada')),
            ],
            options={
                'db_table': 'ocupação',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeículoDisponível',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_veículo', models.BigIntegerField()),
                ('chapa_veículo', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'veículo_disponível',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VagaLivre',
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'managed': False, 'ordering': ['nome_modelo']},
        ),
    ]
