# Generated by Django 3.2.9 on 2021-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_auto_20211117_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='veículodisponível',
            table='veículodisponível',
        ),
    ]
